"""
Django settings for hed_project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega o .env explicitamente da raiz do projeto
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dzd((_1f)u%d@kq+d)a)s3%lu)$@3&gx*=bvh*x4c210zp6f&%')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'signage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hed_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hed_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

if os.environ.get('SUPABASE_DB_HOST'):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('SUPABASE_DB_NAME', 'postgres'),
        'USER': os.environ.get('SUPABASE_DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('SUPABASE_DB_PASSWORD', ''),
        'HOST': os.environ.get('SUPABASE_DB_HOST', ''),
        'PORT': os.environ.get('SUPABASE_DB_PORT', '5432'),
        'CONN_MAX_AGE': 600,
        'CONN_HEALTH_CHECKS': True,
    }


# ==============================================================================
# AUTENTICAÇÃO
# ==============================================================================

AUTH_USER_MODEL = 'signage.Usuario'

AUTHENTICATION_BACKENDS = [
    'signage.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# ==============================================================================
# CORS (Cross-Origin Resource Sharing) - Configuração Estrita
# ==============================================================================
# Em desenvolvimento (DEBUG=True), permite todas as origens para facilitar.
# Em produção (DEBUG=False), apenas os domínios listados são aceitos.

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173'
    ).split(',')

# Headers permitidos nas requisições cross-origin
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control',
]

# Métodos HTTP permitidos
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Permite envio de cookies/credenciais cross-origin (necessário para JWT refresh)
CORS_ALLOW_CREDENTIALS = True


# ==============================================================================
# DJANGO REST FRAMEWORK - Segurança e Throttling
# ==============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Rate Limiting global para proteção contra abuso
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '500/hour',        # Usuários não autenticados: 500 req/hora
        'user': '2000/hour',       # Usuários autenticados: 2000 req/hora
        'login': '10/minute',      # Login (JWT): 10 tentativas/minuto (anti brute-force)
        'register': '5/minute',    # Registro: 5 tentativas/minuto (anti spam)
        'password_reset': '10/hour',  # Password reset: 10 tentativas/hora (anti abuso)
    },
    # Desabilita o browsable API em produção
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ) if not DEBUG else (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
}


# ==============================================================================
# SIMPLE JWT - Tokens de Acesso
# ==============================================================================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
    # Para ativar rotação de tokens em produção (requer migrate após adicionar token_blacklist):
    # 'ROTATE_REFRESH_TOKENS': True,
    # 'BLACKLIST_AFTER_ROTATION': True,
}


# ==============================================================================
# SECURITY HEADERS & MIDDLEWARES
# ==============================================================================

# Proteção contra XSS (Cross-Site Scripting)
# Instrui o navegador a ativar o filtro XSS embutido
SECURE_BROWSER_XSS_FILTER = True

# Impede o navegador de "adivinhar" o Content-Type (MIME sniffing)
SECURE_CONTENT_TYPE_NOSNIFF = True

# Proteção contra Clickjacking - impede que o site seja embutido em iframes
X_FRAME_OPTIONS = 'DENY'

# Referrer Policy - limita informações enviadas no header Referer
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Permissões de funcionalidades do navegador (câmera, microfone, geolocalização)
PERMISSIONS_POLICY = {
    'camera': [],
    'microphone': [],
    'geolocation': [],
}

# ==============================================================================
# CONFIGURAÇÕES PARA PRODUÇÃO COM HTTPS
# ==============================================================================
# Ative as linhas abaixo APENAS quando o deploy estiver com HTTPS configurado.
# Em desenvolvimento local (HTTP), mantenha comentado para evitar erros.
#
# SECURE_SSL_REDIRECT = True              # Redireciona todo HTTP para HTTPS
# SECURE_HSTS_SECONDS = 31536000          # HSTS: força HTTPS por 1 ano
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True   # Aplica HSTS a subdomínios
# SECURE_HSTS_PRELOAD = True              # Permite inclusão na lista de preload
# SESSION_COOKIE_SECURE = True            # Cookie de sessão só via HTTPS
# CSRF_COOKIE_SECURE = True               # Cookie CSRF só via HTTPS
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Para proxies reversos


# ==============================================================================
# PASSWORD VALIDATION
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 6}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ==============================================================================
# INTERNACIONALIZAÇÃO
# ==============================================================================

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True


# ==============================================================================
# ARQUIVOS ESTÁTICOS
# ==============================================================================

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# EMAIL SERVICE CONFIGURATION
# ==============================================================================

EMAIL_API_KEY = os.environ.get('EMAIL_API_KEY', '')
EMAIL_FROM_ADDRESS = os.environ.get('EMAIL_FROM_ADDRESS', '')
EMAIL_PROVIDER = os.environ.get('EMAIL_PROVIDER', 'emailjs')
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# EmailJS Configuration
EMAILJS_SERVICE_ID = os.environ.get('EMAILJS_SERVICE_ID', '')
EMAILJS_USER_ID = os.environ.get('EMAILJS_USER_ID', '')
EMAILJS_TEMPLATE_CREDENTIALS_ID = os.environ.get('EMAILJS_TEMPLATE_CREDENTIALS_ID', '')
EMAILJS_TEMPLATE_RESET_ID = os.environ.get('EMAILJS_TEMPLATE_RESET_ID', '')
EMAILJS_PRIVATE_KEY = os.environ.get('EMAILJS_PRIVATE_KEY', '')
