# Generated by Django 6.0.5 on 2026-05-15 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campanha',
            name='duracao',
            field=models.PositiveIntegerField(choices=[(15, '15 Segundos'), (30, '30 Segundos'), (60, '60 Segundos')], default=15),
        ),
        migrations.AddField(
            model_name='campanha',
            name='turno',
            field=models.CharField(choices=[('MANHA', 'Manhã (07:00 - 11:59)'), ('TARDE', 'Tarde (12:00 - 17:59)'), ('NOITE', 'Noite/Madrugada (18:00 - 06:59)'), ('INTEGRAL', 'Integral (Todos os Turnos)')], default='INTEGRAL', max_length=20),
        ),
        migrations.CreateModel(
            name='CampanhaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tocado_em', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='signage.campanha')),
            ],
        ),
    ]
