# Generated by Django 6.0.5 on 2026-05-17 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0002_campanha_categoria_campanha_duracao_campanha_turno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_str', models.CharField(help_text='Nome de usuário para auditoria', max_length=150)),
                ('acao', models.CharField(choices=[('LOGIN_SUCESSO', 'Tentativa de Login (Sucesso)'), ('LOGIN_FALHA', 'Tentativa de Login (Falha)'), ('CAMPANHA_CRIACAO', 'Criação de Campanha'), ('CAMPANHA_APROVACAO', 'Aprovação de Campanha'), ('CAMPANHA_EXCLUSAO', 'Exclusão de Campanha'), ('CAMPANHA_PAUSA', 'Pausa de Campanha'), ('UPLOAD_VIDEO', 'Upload de Vídeo/Imagem'), ('REGISTRO_PARCEIRO', 'Cadastro de Parceiro')], max_length=50)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
