# Generated by Django 6.0.5 on 2026-05-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0003_auditorialog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='turno',
            field=models.CharField(choices=[('MANHA', 'Manhã (06:00 - 11:59)'), ('TARDE', 'Tarde (12:00 - 17:59)'), ('NOITE', 'Noite (18:00 - 23:59)'), ('MADRUGADA', 'Madrugada (00:00 - 05:59)'), ('INTEGRAL', 'Integral (Todos os Turnos)')], default='INTEGRAL', max_length=20),
        ),
    ]
