# Generated by Django 6.0.5 on 2026-05-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0004_alter_campanha_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='status',
            field=models.CharField(choices=[('EM_ANALISE', 'Em Análise'), ('APROVADA', 'Aprovada'), ('ATIVA', 'Ativa'), ('PAUSADA', 'Pausada'), ('EXPIRADA', 'Expirada')], default='EM_ANALISE', max_length=20),
        ),
    ]
