# Generated by Django 6.0.5 on 2026-05-18 16:26

import signage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0005_alter_campanha_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='dias_semana',
            field=models.JSONField(default=signage.models.default_dias_semana, help_text='Lista de dias da semana (ex: [0, 1, 2]) onde 0 é Segunda-feira e 6 é Domingo.'),
        ),
    ]
