# Generated by Django 6.0.5 on 2026-05-18 16:56

import signage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0006_campanha_dias_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanha',
            name='turno',
        ),
        migrations.AddField(
            model_name='campanha',
            name='turnos',
            field=models.JSONField(default=signage.models.default_turnos, help_text='Lista de turnos selecionados.'),
        ),
    ]
