# Generated by Django 6.0.5 on 2026-05-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0007_remove_campanha_turno_campanha_turnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='is_institucional',
            field=models.BooleanField(default=False, help_text='Se True, é uma campanha institucional do hospital usada para preencher tempo ocioso.'),
        ),
    ]
