# Generated by Django 6.0.5 on 2026-05-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0008_campanha_is_institucional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorialog',
            name='acao',
            field=models.CharField(choices=[('LOGIN_SUCESSO', 'Tentativa de Login (Sucesso)'), ('LOGIN_FALHA', 'Tentativa de Login (Falha)'), ('CAMPANHA_CRIACAO', 'Criação de Campanha'), ('CAMPANHA_EDICAO', 'Edição de Campanha'), ('CAMPANHA_APROVACAO', 'Aprovação de Campanha'), ('CAMPANHA_EXCLUSAO', 'Exclusão de Campanha'), ('CAMPANHA_PAUSA', 'Pausa de Campanha'), ('CAMPANHA_EXPIRADA', 'Campanha Expirada'), ('UPLOAD_VIDEO', 'Upload de Vídeo/Imagem'), ('REGISTRO_PARCEIRO', 'Cadastro de Parceiro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='status',
            field=models.CharField(choices=[('EM_ANALISE', 'Pendente'), ('APROVADA', 'Aprovada'), ('ATIVA', 'Ativa'), ('PAUSADA', 'Pausada'), ('EXPIRADA', 'Expirada')], default='EM_ANALISE', max_length=20),
        ),
    ]
