# Generated by Django 6.0.5 on 2026-05-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0009_alter_auditorialog_acao_alter_campanha_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='duracao',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
