# Generated by Django 6.0.5 on 2026-05-21 12:41

import signage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0010_alter_campanha_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='tvs',
            field=models.JSONField(default=signage.models.default_tvs, help_text='Lista de TVs selecionadas.'),
        ),
    ]
