# Generated by Django 6.0.5 on 2026-05-28 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0011_campanha_tvs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único de autenticação do dispositivo.', unique=True)),
                ('nome', models.CharField(help_text='Nome identificador do monitor (ex: TV Recepção 01)', max_length=100)),
                ('localizacao', models.CharField(choices=[('sala_espera', 'Sala de Espera'), ('recepcao', 'Recepção'), ('sala_cirurgia', 'Sala de Cirurgia'), ('corredor', 'Corredor Principal')], help_text='Local físico onde a TV está instalada.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Se False, o token é revogado e a TV não recebe mais conteúdo.')),
                ('ultimo_ping', models.DateTimeField(blank=True, help_text='Último momento em que o player fez uma requisição.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monitor TV',
                'verbose_name_plural': 'Monitores TV',
            },
        ),
        migrations.CreateModel(
            name='AnaliseIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('classificacao', models.CharField(blank=True, choices=[('SEGURO', 'Seguro'), ('ATENCAO', 'Atenção'), ('IMPROPRIO', 'Impróprio')], max_length=20, null=True)),
                ('score_seguro', models.FloatField(blank=True, help_text='Score 0-1 de conteúdo seguro (média dos frames)', null=True)),
                ('score_nsfw', models.FloatField(blank=True, help_text='Score 0-1 de conteúdo NSFW (média dos frames)', null=True)),
                ('detalhes', models.JSONField(blank=True, help_text='Resposta completa da API por frame analisado', null=True)),
                ('erro_mensagem', models.TextField(blank=True, null=True)),
                ('analisado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analise_ia', to='signage.campanha')),
            ],
            options={
                'verbose_name': 'Análise IA',
                'verbose_name_plural': 'Análises IA',
            },
        ),
    ]
