# Generated by Django 6.0.5 on 2026-05-29 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0012_monitortv_analiseia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorialog',
            name='acao',
            field=models.CharField(choices=[('LOGIN_SUCESSO', 'Tentativa de Login (Sucesso)'), ('LOGIN_FALHA', 'Tentativa de Login (Falha)'), ('CAMPANHA_CRIACAO', 'Criação de Campanha'), ('CAMPANHA_EDICAO', 'Edição de Campanha'), ('CAMPANHA_APROVACAO', 'Aprovação de Campanha'), ('CAMPANHA_EXCLUSAO', 'Exclusão de Campanha'), ('CAMPANHA_PAUSA', 'Pausa de Campanha'), ('CAMPANHA_EXPIRADA', 'Campanha Expirada'), ('UPLOAD_VIDEO', 'Upload de Vídeo/Imagem'), ('REGISTRO_PARCEIRO', 'Cadastro de Parceiro'), ('EMAIL_CREDENCIAIS', 'Envio de Credenciais por E-mail'), ('EMAIL_CREDENCIAIS_FALHA', 'Falha no Envio de Credenciais'), ('SENHA_REDEFINIDA', 'Redefinição de Senha')], max_length=50),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AnaliseIA',
        ),
    ]
