# Generated by Django 6.0.5 on 2026-05-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0013_alter_auditorialog_acao_passwordresettoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorialog',
            name='acao',
            field=models.CharField(choices=[('LOGIN_SUCESSO', 'Tentativa de Login (Sucesso)'), ('LOGIN_FALHA', 'Tentativa de Login (Falha)'), ('CAMPANHA_CRIACAO', 'Criação de Campanha'), ('CAMPANHA_EDICAO', 'Edição de Campanha'), ('CAMPANHA_APROVACAO', 'Aprovação de Campanha'), ('CAMPANHA_EXCLUSAO', 'Exclusão de Campanha'), ('CAMPANHA_PAUSA', 'Pausa de Campanha'), ('CAMPANHA_EXPIRADA', 'Campanha Expirada'), ('UPLOAD_VIDEO', 'Upload de Vídeo/Imagem'), ('REGISTRO_PARCEIRO', 'Cadastro de Parceiro'), ('EMAIL_CREDENCIAIS', 'Envio de Credenciais por E-mail'), ('EMAIL_CREDENCIAIS_FALHA', 'Falha no Envio de Credenciais'), ('SENHA_REDEFINIDA', 'Redefinição de Senha'), ('EDICAO_USUARIO', 'Edição de Usuário'), ('EXCLUSAO_USUARIO', 'Exclusão de Usuário')], max_length=50),
        ),
    ]
